import type { Lang } from '../app';

export const workbenchCopy = {
  zh: {
    nav: '工作台',
    title: '工作台',
    intro: '框选修补错字、恢复可编辑文本、按原图像素裁剪，并以无损 PNG 导出。',
    sidebar: {
      projects: '工程',
      properties: '属性',
      layers: '修补区域'
    },
    projects: {
      title: '工程',
      count: (n: number) => `${n} 个工程`,
      empty: '还没有工程。导入图片，或在结果页、历史页点击「在工作台编辑」。',
      import: '导入图片',
      blank: '新建空白工程',
      copy: '复制当前工程',
      rename: '重命名',
      remove: '删除',
      confirmRemove: '确认删除',
      collapse: '收起工程栏',
      expand: '展开工程栏',
      size: (w: number, h: number) => `${w} × ${h}`,
      resumed: '已打开该图片最近编辑的工程',
      created: '已创建新工程',
      removed: '工程已删除',
      removeFailed: '删除工程失败',
      openFailed: '打开工程失败',
      renamePrompt: '工程名称',
      loadFailed: '加载工程列表失败'
    },
    tools: {
      select: '选择 (V)',
      rect: '矩形修补 (R)',
      ellipse: '椭圆修补 (E)',
      eyedropper: '吸管 (I)',
      text: '文字 (T)',
      crop: '裁剪 (C)',
      undo: '撤销',
      redo: '重做',
      original: '按住查看原图',
      compare: '对比线',
      restore: '恢复到原图',
      export: '导出 PNG',
      fit: '适应窗口',
      zoomIn: '放大',
      zoomOut: '缩小'
    },
    status: {
      zoom: (pct: number) => `${pct}%`,
      source: (w: number, h: number) => `源图 ${w} × ${h}`,
      crop: (w: number, h: number) => `裁剪后 ${w} × ${h}`,
      clean: '已保存',
      dirty: '修改未保存',
      saving: '正在保存…',
      saved: '已保存',
      failed: '保存失败',
      retry: '重试'
    },
    pending: {
      analyzing: '正在分析底色…',
      ocrRunning: '正在识别文字…',
      found: (n: number) => `识别到 ${n} 行文字`,
      none: '未识别到可靠文字',
      unavailable: 'OCR 组件未安装，仅覆盖底色',
      failed: 'OCR 识别失败，仅覆盖底色',
      apply: '应用修补',
      cancel: '取消',
      install: '安装 OCR 组件',
      uneven: '背景可能不均匀'
    },
    inspector: {
      nothing: '选中修补区域或文本后在此调整属性；裁剪模式下显示裁剪参数。',
      shape: '形状',
      rect: '矩形',
      ellipse: '椭圆',
      position: '位置',
      size: '尺寸',
      fill: '填充色',
      autoValue: '自动识别值',
      manual: '手工',
      auto: '自动',
      reanalyze: '重新识别主色',
      resetAuto: '恢复自动值',
      eyedropper: '吸管取色',
      uneven: '背景可能不均匀，已按面积最大的颜色覆盖，可手工修正。',
      ocr: 'OCR',
      ocrStatus: {
        pending: '等待识别',
        none: '未识别到可靠文字',
        found: '已生成文字',
        unreliable: '未识别到可靠文字',
        unavailable: 'OCR 组件未安装',
        failed: '识别失败',
        '': '—'
      },
      stale: '选区已变化，文字可能需要重新识别',
      reocr: '重新识别文字',
      reocrConfirm: '重新识别会替换该区域现有的 OCR 子文本层（包括人工修改），是否继续？',
      addText: '添加文字',
      mergeTexts: '合并为一个文本框',
      content: '内容',
      font: '字体',
      fontRecommended: '覆盖当前字符',
      fontOther: '其他字体',
      fontMissing: (name: string) => `字体「${name}」在本机不可用，预览使用回退字体`,
      fontSize: '字号',
      weight: '粗细',
      italic: '斜体',
      color: '颜色',
      align: '水平对齐',
      valign: '垂直对齐',
      left: '左',
      center: '中',
      right: '右',
      top: '上',
      middle: '中',
      bottom: '下',
      lineHeight: '行距',
      letterSpacing: '字间距',
      autoFit: '自动适配',
      overflow: '文字超出文本框',
      unlink: '解除关联',
      link: '关联到修补区域',
      linkTarget: '选择修补区域',
      visible: '显示',
      hidden: '隐藏',
      up: '上移',
      down: '下移',
      duplicate: '复制',
      remove: '删除',
      groupLabel: (shape: string, n: number) => `${shape}修补 · ${n} 段文字`,
      textLabel: '文本',
      independent: '独立文本',
      layersEmpty: '还没有修补区域。用矩形或椭圆工具在图上框选。',
      cropTitle: '裁剪',
      aspect: '比例',
      aspectFree: '自由',
      aspectOriginal: '原始',
      aspectCustom: '自定义',
      flipX: '水平翻转',
      flipY: '垂直翻转',
      resetCrop: '重置裁剪',
      applyCrop: '完成裁剪',
      cropHint: '裁剪框吸附到原图整数像素；导出尺寸严格等于裁剪框覆盖的像素。'
    },
    exportDialog: {
      title: '导出 PNG',
      size: (w: number, h: number) => `输出尺寸：${w} × ${h} 像素（无损 PNG，不透明）`,
      missingFonts: (names: string) => `以下字体在本机不可用，将使用内置回退字体：${names}`,
      alpha: '源图含透明像素，已按白色背景合成。',
      confirm: '选择位置并导出',
      cancel: '取消',
      done: (name: string) => `已导出 ${name}`,
      failed: '导出失败',
      needSave: '导出前需要先保存工程',
      defaultName: (stem: string) => `${stem}_已编辑.png`
    },
    ocrDialog: {
      title: '安装 OCR 组件',
      body: (mib: string) => `识别文字需要下载 PP-OCRv6 medium 检测、识别模型与文字方向分类模型，约 ${mib}。识别引擎已内置，下载后全程离线运行，图片不会上传。`,
      location: (dir: string) => `存储位置：${dir}`,
      license: (license: string) => `模型许可证：${license}`,
      install: '开始下载',
      cancel: '取消',
      downloading: (done: string, total: string) => `正在下载 ${done} / ${total}`,
      verifying: '正在校验…',
      done: 'OCR 组件已就绪',
      failed: '下载失败',
      cancelled: '下载已取消',
      retry: '重试',
      close: '关闭'
    },
    restoreConfirm: '恢复到原图将清空全部修补、文字和裁剪，源图片不受影响。是否继续？',
    leave: {
      title: '有修改尚未保存',
      body: (reason: string) => `保存失败：${reason}`,
      retry: '重试保存',
      discard: '放弃修改',
      stay: '留在工作台'
    },
    settings: {
      title: '工作台',
      storage: '工程与源图快照',
      storageLine: (projects: number, projectBytes: string, assets: number, assetBytes: string) =>
        `${projects} 个工程（${projectBytes}），${assets} 份源图快照（${assetBytes}）`,
      unreferenced: (n: number, bytes: string) => `其中 ${n} 份快照已无工程引用（${bytes}）`,
      cleanup: '清理无引用快照',
      cleaned: (n: number, bytes: string) => `已清理 ${n} 份快照，释放 ${bytes}`,
      ocr: 'OCR 组件',
      ocrEngine: (version: string, runtime: string, running: boolean) =>
        `内置识别引擎 dreampaper-ocr ${version}（ONNX Runtime ${runtime}，随应用升级）${running ? ' · 正在运行' : ''}`,
      ocrEngineMissing: (problem: string) => `内置识别引擎不可用：${problem}`,
      ocrInstalled: (version: string, bytes: string) => `模型已安装 ${version}，占用 ${bytes}`,
      ocrMissing: (bytes: string) => `模型未安装（下载约 ${bytes}）`,
      ocrInstall: '下载安装',
      ocrRedownload: '重新下载',
      ocrRemove: '删除组件',
       ocrCheck: '检查更新',
       ocrUpToDate: '模型清单已是应用内置的最新版本',
       ocrRemoveConfirm: '删除 OCR 组件后，已有工程仍会保留，但新的文字识别将不可用。是否继续？',
       cleanupConfirm: '只清理没有任何工程引用的源图快照。是否继续？',
       refresh: '刷新'
    },
    entry: '在工作台编辑',
    messages: {
      analyzeFailed: '底色分析失败',
      ocrFailed: 'OCR 识别失败',
      measureFailed: '文字测量失败',
      copyDone: '已复制工程',
      restoreDone: '已恢复到原图'
    }
  },
  en: {
    nav: 'Workbench',
    title: 'Workbench',
    intro: 'Cover wrong text, recover editable text, crop at source pixels and export lossless PNG.',
    sidebar: {
      projects: 'Projects',
      properties: 'Properties',
      layers: 'Regions'
    },
    projects: {
      title: 'Projects',
      count: (n: number) => `${n} project(s)`,
      empty: 'No projects yet. Import an image, or use "Edit in workbench" on a result or history card.',
      import: 'Import image',
      blank: 'New blank project',
      copy: 'Duplicate project',
      rename: 'Rename',
      remove: 'Delete',
      confirmRemove: 'Confirm delete',
      collapse: 'Collapse projects',
      expand: 'Expand projects',
      size: (w: number, h: number) => `${w} × ${h}`,
      resumed: 'Opened the most recent project for this image',
      created: 'Created a new project',
      removed: 'Project deleted',
      removeFailed: 'Failed to delete project',
      openFailed: 'Failed to open project',
      renamePrompt: 'Project name',
      loadFailed: 'Failed to load projects'
    },
    tools: {
      select: 'Select (V)',
      rect: 'Rectangle repair (R)',
      ellipse: 'Ellipse repair (E)',
      eyedropper: 'Eyedropper (I)',
      text: 'Text (T)',
      crop: 'Crop (C)',
      undo: 'Undo',
      redo: 'Redo',
      original: 'Hold to view original',
      compare: 'Compare slider',
      restore: 'Restore original',
      export: 'Export PNG',
      fit: 'Fit to window',
      zoomIn: 'Zoom in',
      zoomOut: 'Zoom out'
    },
    status: {
      zoom: (pct: number) => `${pct}%`,
      source: (w: number, h: number) => `Source ${w} × ${h}`,
      crop: (w: number, h: number) => `Crop ${w} × ${h}`,
      clean: 'Saved',
      dirty: 'Unsaved changes',
      saving: 'Saving…',
      saved: 'Saved',
      failed: 'Save failed',
      retry: 'Retry'
    },
    pending: {
      analyzing: 'Analysing background…',
      ocrRunning: 'Recognising text…',
      found: (n: number) => `${n} text line(s) recognised`,
      none: 'No reliable text found',
      unavailable: 'OCR not installed; fill only',
      failed: 'OCR failed; fill only',
      apply: 'Apply repair',
      cancel: 'Cancel',
      install: 'Install OCR',
      uneven: 'Background may be uneven'
    },
    inspector: {
      nothing: 'Select a repair region or text to edit its properties; crop mode shows crop settings.',
      shape: 'Shape',
      rect: 'Rectangle',
      ellipse: 'Ellipse',
      position: 'Position',
      size: 'Size',
      fill: 'Fill',
      autoValue: 'Detected',
      manual: 'Manual',
      auto: 'Auto',
      reanalyze: 'Re-detect colour',
      resetAuto: 'Use detected',
      eyedropper: 'Eyedropper',
      uneven: 'The background may be uneven; the largest colour area was used. Adjust by hand if needed.',
      ocr: 'OCR',
      ocrStatus: {
        pending: 'Pending',
        none: 'No reliable text',
        found: 'Text created',
        unreliable: 'No reliable text',
        unavailable: 'OCR not installed',
        failed: 'Recognition failed',
        '': '—'
      },
      stale: 'Region changed; text may need re-recognition',
      reocr: 'Re-recognise text',
      reocrConfirm: 'This replaces the OCR text layers in this region, including manual edits. Continue?',
      addText: 'Add text',
      mergeTexts: 'Merge into one box',
      content: 'Content',
      font: 'Font',
      fontRecommended: 'Covers current text',
      fontOther: 'Other fonts',
      fontMissing: (name: string) => `Font "${name}" is not available here; preview uses the fallback font`,
      fontSize: 'Size',
      weight: 'Weight',
      italic: 'Italic',
      color: 'Colour',
      align: 'Align',
      valign: 'Vertical',
      left: 'Left',
      center: 'Center',
      right: 'Right',
      top: 'Top',
      middle: 'Middle',
      bottom: 'Bottom',
      lineHeight: 'Line height',
      letterSpacing: 'Letter spacing',
      autoFit: 'Auto fit',
      overflow: 'Text overflows its box',
      unlink: 'Detach',
      link: 'Attach to region',
      linkTarget: 'Choose region',
      visible: 'Show',
      hidden: 'Hide',
      up: 'Move up',
      down: 'Move down',
      duplicate: 'Duplicate',
      remove: 'Delete',
      groupLabel: (shape: string, n: number) => `${shape} repair · ${n} text`,
      textLabel: 'Text',
      independent: 'Independent text',
      layersEmpty: 'No repair regions yet. Draw one with the rectangle or ellipse tool.',
      cropTitle: 'Crop',
      aspect: 'Aspect',
      aspectFree: 'Free',
      aspectOriginal: 'Original',
      aspectCustom: 'Custom',
      flipX: 'Flip horizontal',
      flipY: 'Flip vertical',
      resetCrop: 'Reset crop',
      applyCrop: 'Done',
      cropHint: 'The crop snaps to source pixels; the export is exactly the pixels it covers.'
    },
    exportDialog: {
      title: 'Export PNG',
      size: (w: number, h: number) => `Output: ${w} × ${h} px (lossless, opaque PNG)`,
      missingFonts: (names: string) => `Unavailable fonts will use the bundled fallback: ${names}`,
      alpha: 'The source has transparency; it is composited on white.',
      confirm: 'Choose location and export',
      cancel: 'Cancel',
      done: (name: string) => `Exported ${name}`,
      failed: 'Export failed',
      needSave: 'The project must be saved before exporting',
      defaultName: (stem: string) => `${stem}_edited.png`
    },
    ocrDialog: {
      title: 'Install OCR component',
      body: (mib: string) => `Text recognition downloads the PP-OCRv6 medium detection and recognition models plus the line-orientation classifier (about ${mib}). The engine is built in; afterwards OCR runs fully offline and images never leave this computer.`,
      location: (dir: string) => `Location: ${dir}`,
      license: (license: string) => `Model license: ${license}`,
      install: 'Download',
      cancel: 'Cancel',
      downloading: (done: string, total: string) => `Downloading ${done} / ${total}`,
      verifying: 'Verifying…',
      done: 'OCR component ready',
      failed: 'Download failed',
      cancelled: 'Download cancelled',
      retry: 'Retry',
      close: 'Close'
    },
    restoreConfirm: 'Restoring the original clears every repair, text and crop. The source image is untouched. Continue?',
    leave: {
      title: 'Unsaved changes',
      body: (reason: string) => `Save failed: ${reason}`,
      retry: 'Retry save',
      discard: 'Discard changes',
      stay: 'Stay'
    },
    settings: {
      title: 'Workbench',
      storage: 'Projects and source snapshots',
      storageLine: (projects: number, projectBytes: string, assets: number, assetBytes: string) =>
        `${projects} project(s) (${projectBytes}), ${assets} snapshot(s) (${assetBytes})`,
      unreferenced: (n: number, bytes: string) => `${n} snapshot(s) no longer referenced (${bytes})`,
      cleanup: 'Clean unreferenced snapshots',
      cleaned: (n: number, bytes: string) => `Removed ${n} snapshot(s), freed ${bytes}`,
      ocr: 'OCR component',
      ocrEngine: (version: string, runtime: string, running: boolean) =>
        `Built-in engine dreampaper-ocr ${version} (ONNX Runtime ${runtime}, updated with the app)${running ? ' · running' : ''}`,
      ocrEngineMissing: (problem: string) => `Built-in engine unavailable: ${problem}`,
      ocrInstalled: (version: string, bytes: string) => `Models installed ${version}, ${bytes} on disk`,
      ocrMissing: (bytes: string) => `Models not installed (about ${bytes} download)`,
      ocrInstall: 'Download',
      ocrRedownload: 'Re-download',
      ocrRemove: 'Remove',
       ocrCheck: 'Check for updates',
       ocrUpToDate: 'The model manifest matches the latest bundled version',
       ocrRemoveConfirm: 'Removing OCR keeps existing projects but disables new recognition. Continue?',
       cleanupConfirm: 'Only source snapshots with no project references will be removed. Continue?',
       refresh: 'Refresh'
    },
    entry: 'Edit in workbench',
    messages: {
      analyzeFailed: 'Colour analysis failed',
      ocrFailed: 'OCR failed',
      measureFailed: 'Text measurement failed',
      copyDone: 'Project duplicated',
      restoreDone: 'Restored to original'
    }
  }
} as const;

export type WorkbenchCopy = (typeof workbenchCopy)[Lang];

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const units = ['KiB', 'MiB', 'GiB'];
  let value = bytes / 1024;
  let unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit += 1;
  }
  return `${value >= 100 ? value.toFixed(0) : value.toFixed(1)} ${units[unit]}`;
}
